USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
PROJECTS_PAGINATE_BY = 12
MAX_SKILLS_SEARCH_RESULTS = 10
PROJECT_STATUS_OPEN = 'open'
PROJECT_STATUS_CLOSED = 'closed'

USER_PHONE_MAX_LEN = 12
USER_ABOUT_MAX_LEN = 256

SKILL_NAME_MAX_LEN = 100

PROJECT_NAME_MAX_LEN = 200
PROJECT_STATUS_MAX_LEN = 10

CHOICES = [
    (PROJECT_STATUS_OPEN, 'Открыт'),
    (PROJECT_STATUS_CLOSED, 'Закрыт'),
]

AVATAR_SIZE = 200
AVATAR_FONT_RATIO = 0.7
AVATAR_FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
AVATAR_SATURATION_MIN = 0.3
AVATAR_SATURATION_MAX = 0.5
AVATAR_VALUE_MIN = 0.8
AVATAR_VALUE_MAX = 0.95
AVATAR_TEXT_COLOR = (50, 50, 50)
