USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
PROJECTS_PAGINATE_BY = 12
MAX_SKILLS_SEARCH_RESULTS = 10
PROJECT_STATUS_OPEN = 'open'
PROJECT_STATUS_CLOSED = 'closed'

USER_PHONE_MAX_LEN = 12
USER_ABOUT_MAX_LEN = 256

SKILL_NAME_MAX_LEN = 100

PROJECT_NAME_MAX_LEN = 200
PROJECT_STATUS_MAX_LEN = 10

CHOICES = [
    (PROJECT_STATUS_OPEN, 'Открыт'),
    (PROJECT_STATUS_CLOSED, 'Закрыт'),
]
